### PR TITLE
Add TypeScript type declaration

### PR DESCRIPTION
**Pull request by goodmind**
/сс @Widdershin

### CODE REVIEW

**Comment by goodmind** [comment]
@Widdershin when you can merge this? Or should I write some type tests like in DefinitelyTyped repository?

**Comment by Widdershin** [comment]
@goodmind if @lmatteis is happy I will merge this. I held off merging because this is @lmatteis and @nickbalestra's project, I'm just the community coordinator. 😸

**Comment by lmatteis** [comment]
I can't really test it because I don't use Typescript. However I trust @Widdershin that's a beneficial thing to have (and that it works). So I'll go ahead and accept it 👍

**Pull request merged**
